version: '2'
services:
    db:
        image: mysql:5.6
        volumes:
            - "./docker/.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pilons
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
    web:
        build: ./docker
        ports:
            - "5000:5000"
    redis:
        image: "redis:alpine"
